### ISSUE TITLE
slice::get_unchecked_mut panic

### ISSUE THREAD

**Issue by oeed** [perpetual-ml/perpetual#37]
Thanks for making this, seems very impressive!

I'm just starting out trying to use it directly in Rust but encountering a panic. My code looks as such, my matrix is 86 columns and 774 rows:

```rust
let train_features: Vec<f64> = ...;
let train_targets: Vec<f64> = ...;
assert_eq!(train_features.len(), train_targets.len() * FEATURES_COUNT);

let train_features_matrix = Matrix::new(&train_features, train_targets.len(), FEATURES_COUNT);

let budget = 1.0;
let mut model = PerpetualBooster::default().set_objective(Objective::LogLoss);
model
  .fit(
    &train_features_matrix,
    &targets,
    budget,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
  )
  .unwrap();
  ```

The panic backtrace is below, it's tripping up here: https://github.com/perpetual-ml/perpetual/blob/56cda41e44d32c1e2f2208b964ed6f166e0503bd/src/tree.rs#L71

```
thread 'main' panicked at library/core/src/panicking.rs:218:5:
unsafe precondition(s) violated: slice::get_unchecked_mut requires that the index is within the slice
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d49be02cf6d2e2a01264fcdef1e20c826710c0f5/library/std/src/panicking.rs:681:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/d49be02cf6d2e2a01264fcdef1e20c826710c0f5/library/core/src/panicking.rs:117:22
   2: core::panicking::panic_nounwind_fmt
             at /rustc/d49be02cf6d2e2a01264fcdef1e20c826710c0f5/library/core/src/intrinsics/mod.rs:3818:9
   3: core::panicking::panic_nounwind
             at /rustc/d49be02cf6d2e2a01264fcdef1e20c826710c0f5/library/core/src/panicking.rs:218:5
   4: <usize as core::slice::index::SliceIndex<[T]>>::get_unchecked_mut::precondition_check
             at /Users/xxx/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ub_checks.rs:68:21
   5: <usize as core::slice::index::SliceIndex<[T]>>::get_unchecked_mut
             at /Users/xxx/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ub_checks.rs:75:17
   6: core::slice::<impl [T]>::get_unchecked_mut
             at /Users/xxx/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/mod.rs:707:24
   7: perpetual::tree::Tree::fit
             at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/perpetual-0.7.10/src/tree.rs:71:34
   8: perpetual::booster::PerpetualBooster::fit_trees
             at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/perpetual-0.7.10/src/booster.rs:496:13
   9: perpetual::booster::PerpetualBooster::fit
             at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/perpetual-0.7.10/src/booster.rs:306:13
```

Not quite sure where I'm going wrong, any ideas? Rust version is: `rustc 1.85.0-nightly (d49be02cf 2024-12-02)` and `perpetual = "0.7.10"`

Thanks!

**Comment by deadsoul44** [comment]
You have `train_targets` at the beginning, but you use `target` in the fit method. Maybe you wanted to use `train_targets`? If this is not the cause, could you please provide the data and the full code to reproduce the error?

**Comment by oeed** [comment]
Ah yes, `train_targets` was just a typo in simplifying my example. I can replicate the panic with this min repro:

```rust
// 2 features per target
let features: Vec<f64> = vec![1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0];
let targets: Vec<f64> = vec![1.0, -1.0, 1.0, -1.0, -1.0];

assert_eq!(features.len(), targets.len() * 2);
let matrix = Matrix::new(&features, targets.len(), 2);

let budget = 1.0;
let mut model = PerpetualBooster::default().set_objective(Objective::LogLoss);
model
  .fit(
    &matrix, &targets, budget, None, None, None, None, None, None, None, None,
  )
  .unwrap();
```

**Comment by deadsoul44** [comment]
You have `train_targets` at the beginning, but you use `target` in the fit method. Maybe you wanted to use `train_targets`? If this is not the cause, could you please provide the data and the full code to reproduce the error?

**Comment by oeed** [comment]
I've been testing various inputs and now the original values are working fine – bizarrely. I've only had occasional panics, so perhaps it's something in how it's randomised, or perhaps it simply has an empty tree triggering it.

**Comment by deadsoul44** [comment]
The available memory is checked at the beginning of the fit method. Somehow, this check gives zero available memory probably. Could you please try `memory_limit` parameter to manually set allocated memory for the algorithm?

**Comment by oeed** [comment]
Yeah with a manual limit it works just fine, just seems to be detecting 0 available for some reason.

**Comment by deadsoul44** [comment]
Version 0.7.12 is released with the fix. In this version, the algorithm tries to allocate 100 nodes at minimum if detected memory is zero. If `memory_limit` is specified, 100 node limit is ignored.
